name=Disk Partitions
id=disk_partitions
author=aitorserra
version=1.1.1
update_url=https://github.com/aitorserra/porcentaje_uso_de_disco_directadmin/raw/main/dist/disk_partitions.tar.gz
active=yes
installed=yes
